import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const [logs, setLogs] = useState<string[]>([]);

  const generateLog = () => {
    const logText = `Here is a log generated at => ${new Date()}`;
    const tempArray = [...logs, logText];
    console.log(logText);
    setLogs(tempArray);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Client Logs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <span>Client Logs</span>
        </h1>

        <p className={styles.description}>View logs below or in the console.</p>

        <div className={styles.grid}>
          <button onClick={generateLog} className={styles.card}>
            <h2>Create Log</h2>
          </button>
        </div>

        {logs.length > 0 && (
          <div className={styles.code}>
            {logs.map((log, index) => (
              <p key={index}>{log}</p>
            ))}
          </div>
        )}
      </main>
    </div>
  );
};

export default Home;
